version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: catcin-mongodb
    volumes:
      - ./mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017" 

  backend:
    build: .
    container_name: catcin-backend
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=${MONGO_URL}
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

